language: android
jdk: oraclejdk8
branches:
  only:
  - master
  - develop
android:
  components:
  - tools
  - platform-tools
  - android-26
  - build-tools-26.0.1
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
  - extra-google-google_play_services
  sudo: false
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  - intel-android-extra-license.+
  cache:
    directories:
    - $HOME/.gradle/caches/2.8
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper
before_script:
  - ./code-check.sh
after_success:
  - ./bintray-upload.sh